### ISSUE TITLE
Does bamtofastq work properly for bam files from STARsolo?

### ISSUE THREAD

**Issue by Magisterh1** [10XGenomics/bamtofastq#126]
Hi!

Just a quick question: Does bamtofastq work properly for bam files from STARsolo? And if not, how can I get the fastqs fneeded for cell ranger when I only have STARsolo .bam files?

Thank you!!

**Comment by Magisterh1** [comment]
OK, meanwhile I had a chance to run bamtofastq on some of the files and it seemed to work. 3 different fastq files were generated with the expected read lengths. Afterwards i successfulla ran cellranger and analysed the data using scanpy and scVI. Positive ctrl genes were found as expected and negative ctrl genes were not expressed. So overall, I am quite happy with the results.  Am I missing something? Thank you!!

**Comment by pmarks** [comment]
@Magisterh1 ok, good to know.  I guess STARsolo is implementing the correct tags. Thanks for giving it a try.
