### ISSUE TITLE
fastq directory structure?

### ISSUE THREAD

**Issue by Gibbsdavidl** [10XGenomics/bamtofastq#13]
Hi there,

I ran bamtofastq on the bam file at:
https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/pbmc_1k_protein_v3

And it outputted two directories of fastq files (see image):
![image](https://user-images.githubusercontent.com/561865/62667749-ee14e080-b93d-11e9-8c2d-745014930eb5.png)

What are they?
Thanks!
-dave

**Comment by pmarks** [comment]
Hi @Gibbsdavidl - bamtofastq will create one output for each sequencing library that Cell Ranger was run with.  In this case you have a 'protein' dataset, which means that it includes cell surface protein counts determined using Feature Barcoding antibodies. So one of these directories is the normal gene expression library, and one is the feature barcoding library.  In this case the first library is GEX, and the 2nd library is feature barcoding.  You can see the metadata about the libraries by doing `samtools view -H` on the BAM file.
