### ISSUE TITLE
Unable to convert 10x bam to fastq using bamtofastq and getting folder named as "MissingLibrary"

### ISSUE THREAD

**Issue by biobug16** [10XGenomics/bamtofastq#15]
Hi i have a quick question, i have few aligned bam files from single cell RNA Seq data. I want to regenerate fastqs from them. In order to do so i am using 10x's bamtofastq utility and I am also getting fastq files but in the specified path within a folder named “MissingLibrary_1_flowcellName”. I am not sure what does this mean? Why the generated folder is named as missing library. 
Does anybody have any idea about this?

The command I used is:
`bamtofastq possorted_genome_bam.bam ./sample
`
Any help will be highly appreciated.

Thanks

**Comment by pmarks** [comment]
@biobug16 You'll get "MissingLibrary" in the name of the output folder in some cases when the original run of the pipeline was not able to determine a certain name for the input data.  You can ignore this -- the fastq in the output directory should be fine.

**Comment by aj088** [comment]
> @biobug16 You'll get "MissingLibrary" in the name of the output folder in some cases when the original run of the pipeline was not able to determine a certain name for the input data. You can ignore this -- the fastq in the output directory should be fine.

Then how do you set a certain name for the directory of output data? We don't want a missing library output directory with some random letters.
