### ISSUE TITLE
Output directory doesn't exist error

### ISSUE THREAD

**Issue by Diennguyen8290** [10XGenomics/bamtofastq#26]
Hi,
Thanks for developing the tool.
I'm trying to convert 05 BAM files produced by cellranger (GSE115469) and got the error as follow:
"_bamtofastq v1.3.5
bamtofastqerror: error creating output directory: "/scratch/c.c1942783/Liver.scRNA/fastq/fastqs". Does it already exist?
Please contact patrick@10xgenomics.com for assistance. Please re-run with --traceback and include stack trace with an error report
see below for more details:
error creating output directory: "/scratch/c.c1942783/Liver.scRNA/fastq/fastqs". Does it already exist?_”
Those BAM files are the original ones.
My script is (here is for 01 of those files (https://sra-pub-src-1.s3.amazonaws.com/SRR7276478/P5TLH.bam.1)):
 **bamtofastq P5TLH.bam.1 /scratch/c.c1942783/Liver.scRNA/fastq/fastqs**
The above directory has been created and does exist.
Any help would be greatly appreciated.
Kind regards,
Dien

**Comment by k3yavi** [comment]
hey  @Diennguyen8290 ,

It's complaining because the directory exist, try deleting the directory and running again.

**Comment by Diennguyen8290** [comment]
> hey @Diennguyen8290 ,
> 
> It's complaining because the directory exist, try deleting the directory and running again.

Many thanks for your quick response.
Sorry, I still didn't get it. To my understanding, we need an output folder to save the results and that folder has just created for that purpose. Also, if I delete this directory, how can I specify the output directory in the command line?
Many thanks,
Dien

**Comment by k3yavi** [comment]
Sure, I understand the confusion. You'd have to provide the output directory to the tool but don't create the last directory manually, the tool would do it for you. Basically provide `/scratch/c.c1942783/Liver.scRNA/fastq/fastqs` this as output directory to the tool but don't create the last directory `fastqs`, if you have then delete it. I think that's the problem, I can be wrong.

**Comment by Diennguyen8290** [comment]
> Sure, I understand the confusion. You'd have to provide the output directory to the tool but don't create the last directory manually, the tool would do it for you. Basically provide `/scratch/c.c1942783/Liver.scRNA/fastq/fastqs` this as output directory to the tool but don't create the last directory `fastqs`, if you have then delete it. I think that's the problem, I can be wrong.

@k3yavi 
Thanks for your clarification. Unfortunately it's still there. Even I don't create any new directory and specify the output to the current directory, the error still comes out. I have also tried with older version or with other account and still get the same error. Please could you advise me with the case.
Many thanks.

**Comment by Diennguyen8290** [comment]
> > Sure, I understand the confusion. You'd have to provide the output directory to the tool but don't create the last directory manually, the tool would do it for you. Basically provide `/scratch/c.c1942783/Liver.scRNA/fastq/fastqs` this as output directory to the tool but don't create the last directory `fastqs`, if you have then delete it. I think that's the problem, I can be wrong.
> 
> @k3yavi
> Thanks for your clarification. Unfortunately it's still there. Even I don't create any new directory and specify the output to the current directory, the error still comes out. I have also tried with older version or with other HPC account and still get the same error. Please could you advise me with the case.
> Many thanks.

@k3yavi 
I made an error. It's then solved with that way. 
Many thanks,
Dien
