### ISSUE TITLE
error[E0107]: wrong number of type arguments: expected 1, found 2

### ISSUE THREAD

**Issue by LemonJuice84** [10XGenomics/bamtofastq#4]
I'm trying to install bamtofastq with different version of Rust(v1.28,v.1.32,v1.33) but I always got the following error:

error[E0107]: wrong number of type arguments: expected 1, found 2
   --> src/main.rs:172:21
    |
172 | impl SortKey<SerFq, Vec<u8>> for SerFqSort {
    |                                        ^^^^^^^ unexpected type argument

error: aborting due to previous error

For more information about this error, try `rustc --explain E0107`.
error: Could not compile `bamtofastq`.

**Comment by pmarks** [comment]
Hi @LemonJuice84  - are you using the original Cargo.lock file that comes with the checkout?  It looks like you're using an incompatible version of our shardio library, which could happen if you deleted the Cargo.lock fille, or ran `cargo update`.  Can you re-try with the original Cargo.lock?
