### ISSUE TITLE
Failed to build the release

### ISSUE THREAD

**Issue by anyone1985** [10XGenomics/bamtofastq#9]
Hi,
My os is ubuntu16.04 and I failed to build the release. The following is the error information. I'm not familiar with Rust and Please help me.

--- stderr
./htslib/htslib/hts.h:31:10: fatal error: 'stddef.h' file not found
./htslib/htslib/hts.h:31:10: fatal error: 'stddef.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings.: ()', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by alexvpickering** [comment]
For anyone else who comes across this issue I was able to resolve it by running:

```
sudo apt install clang-3.9
```
